# Generated by Django 2.2.14 on 2021-05-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
